### ISSUE TITLE
Replace Midas with more recent depth models e.g., ZoeDepth, Metric3d-v2, marigold, etc. 

### ISSUE THREAD

**Issue by umariqb** [bytedance/particle-sfm#26]
Hi, 

Thank you so much for the great work. I wonder if replacing MIDAS with more recent models will help improve the SfM quality. Any thoughts? 

Thanks!

**Comment by guohengkai** [comment]
Hi,

Applying more recent depth models will slightly improve the motion segmentation (then more correct points for SfM) because we only use the depth estimation in the motion segmentation module. But it is possible to use the depth to help the initialization and optimization for SfM, like https://arxiv.org/abs/2204.02509.

**Comment by umariqb** [comment]
Thank you for the explanation and reference!
